// Regenerates js/data/breaking.js from the canonical skill-tree JSON
// (dance-mastery/data/breaking-skill-tree.json). The JS module exists so the
// app works over file:// -less static hosting and keeps one source of truth.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "..", "data", "breaking-skill-tree.json");
const outDir = join(here, "..", "js", "data");
const out = join(outDir, "breaking.js");

const tree = JSON.parse(readFileSync(src, "utf8"));
mkdirSync(outDir, { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/sync-data.mjs from dance-mastery/data/breaking-skill-tree.json — do not edit.\nexport default ${JSON.stringify(tree, null, 2)};\n`
);
console.log(`wrote ${out} (${tree.nodes.length} nodes, ${tree.attributes.length} attributes)`);
