// Regenerates app/js/data/<style>.js from every ../data/*-skill-tree.json,
// plus the styles.js registry. One source of truth per style; adding a dance
// is a JSON drop, not code (Doc 04).
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "..", "data");
const outDir = join(here, "..", "js", "data");
mkdirSync(outDir, { recursive: true });

const packs = readdirSync(dataDir)
  .filter((f) => f.endsWith("-skill-tree.json"))
  .sort();

const styles = [];
for (const file of packs) {
  const tree = JSON.parse(readFileSync(join(dataDir, file), "utf8"));
  const id = tree.style;
  if (!id) throw new Error(`${file}: missing "style" field`);
  styles.push(id);
  writeFileSync(
    join(outDir, `${id}.js`),
    `// GENERATED by scripts/sync-data.mjs from data/${file} — do not edit.\nexport default ${JSON.stringify(tree, null, 2)};\n`
  );
  console.log(`wrote js/data/${id}.js (${tree.nodes.length} nodes, ${tree.attributes.length} attributes)`);
}

writeFileSync(
  join(outDir, "styles.js"),
  `// GENERATED by scripts/sync-data.mjs — the style registry. Do not edit.\n` +
  styles.map((s) => `import ${s} from "./${s}.js";`).join("\n") + "\n" +
  `export const STYLES = { ${styles.join(", ")} };\n` +
  `export const DEFAULT_STYLE = ${JSON.stringify(styles.includes("breaking") ? "breaking" : styles[0])};\n` +
  `export function styleName(id) { return STYLES[id]?.name ?? id.charAt(0).toUpperCase() + id.slice(1); }\n` +
  `// Find a node (and its style) by node id across every pack.\n` +
  `export function findNode(nodeId) {\n` +
  `  for (const [style, tree] of Object.entries(STYLES)) {\n` +
  `    const node = tree.nodes.find((n) => n.id === nodeId);\n` +
  `    if (node) return { node, style, tree };\n` +
  `  }\n` +
  `  return null;\n` +
  `}\n`
);
console.log(`wrote js/data/styles.js (${styles.join(", ")})`);

// Global Dance Catalog (data/registry/dance-catalog.json), if present
import { existsSync } from "node:fs";
const catalogSrc = join(dataDir, "registry", "dance-catalog.json");
if (existsSync(catalogSrc)) {
  const catalog = JSON.parse(readFileSync(catalogSrc, "utf8"));
  writeFileSync(
    join(outDir, "catalog.js"),
    `// GENERATED by scripts/sync-data.mjs from data/registry/dance-catalog.json — do not edit.\nexport default ${JSON.stringify(catalog, null, 1)};\n`
  );
  console.log(`wrote js/data/catalog.js (${catalog.styles.length} styles, ${new Set(catalog.styles.map((s) => s.family)).size} families)`);
}
